import React from 'react'
import Layout from '../components/Layout'

const privacyPolicy = () => {
    return (
        <Layout>
            <div className="row justify-content-center">
                <div className="col-8">
                    <h3 className="text-center">Privacy Policy</h3>
                    <br />
                    <p>We respect your privacy and recognize the need to protect the personally identifiable information (any information by which you can be identified, such as name, address, and telephone number) you share with us. We would like to assure you that we follow appropriate standards when it comes to protecting your privacy on our app and website.<br /><br />Some of our web pages use "cookies" so that we can better serve you with customized information when you return to our site. Cookies are identifiers that websites send to the browser on your computer to facilitate your next visit to our site. You can set your browser to notify you when you are sent a cookie, giving you the option to decide whether or not to accept it. The information we collect and analyze is used to improve our service to you.<br /><br />Navigator Tourism collects the following personal sensitive information from you while transacting through Navigator Tourism, this includes your Name and Sex, Phone Number, Billing Address, and Date of birth in case of a child.<br /><br />Navigator Tourism does not sell or trade upon any of the above foregoing information without the consent of the user or customer. The foregoing information collected from the users/customers/travelers is put to the following use:<br /><br />Customer name, address, phone number, traveler’s name, and age are shared with applicable providers like the airlines, hotels, etc., for the purpose of reservation and booking the services for the customer/traveler.<br /><br />Information like Phone number, email address, and billing address may be used for promotional purposes unless the customer/user has unsubscribed from such services. If you choose not to share this information, you can still visit the Navigator Tourism website, but you may be unable to access certain options, offers, and services.<br /><br />Navigator Tourism takes appropriate steps to protect the information you share with us. We have implemented technology and security features and strict policy guidelines to safeguard the privacy of your personally identifiable information from unauthorized access and improper use or disclosure. Please contact us at info@navigatortourism.com to obtain the names and addresses of the specific entities that shall have access to your personal information in a given transaction.<br /><br />You can request the deletion of your information by contacting us.<br /><br />Navigator Tourism will continue to enhance its security procedures as new technology becomes available, and ensures that its security procedures are compliant with current applicable regulations.<br /><br />If our privacy policy changes in the future, it will be posted here and a new effective date will be shown. You should access our privacy policy regularly to ensure you understand our current policies.<br /><br />*All prices and offers are subject to change with availability.</p>

                    <p>আমরা আপনার গোপনীয়তাকে সম্মান করি এবং আপনি আমাদের সাথে শেয়ার করেন এমন ব্যক্তিগত শনাক্তযোগ্য তথ্য (যে কোনো তথ্য যার দ্বারা আপনাকে চিহ্নিত করা যায়, যেমন নাম, ঠিকানা এবং টেলিফোন নম্বর) রক্ষা করার প্রয়োজনীয়তা স্বীকার করি। আমরা আপনাকে আশ্বস্ত করতে চাই যে আমাদের অ্যাপ এবং ওয়েবসাইটে আপনার গোপনীয়তা রক্ষা করার ক্ষেত্রে আমরা উপযুক্ত মান অনুসরণ করি।<br /><br />আমাদের কিছু ওয়েব পৃষ্ঠা "কুকিজ" ব্যবহার করে যাতে আপনি যখন আমাদের সাইটে ফিরে আসেন তখন আমরা আপনাকে কাস্টমাইজড তথ্য দিয়ে আরও ভালো পরিবেশন করতে পারি। কুকিজ হল শনাক্তকারী যা ওয়েবসাইটগুলি আপনার কম্পিউটারের ব্রাউজারে পাঠায় যাতে আমাদের সাইটে আপনার পরবর্তী ভিজিট করা যায়। আপনা কে একটি কুকি পাঠানো হলে আপনাকে অবহিত করার জন্য আপনার ব্রাউজার সেট করতে পারেন, আপনাকে এটি গ্রহণ করবেন কিনা তা সিদ্ধান্ত নেওয়ার বিকল্প দিতে পারেন৷ আমরা যে তথ্য সংগ্রহ করি এবং বিশ্লেষণ করি তা আপনার জন্য আমাদের পরিষেবা উন্নত করতে ব্যবহার করা হয়।<br /><br />নেভিগেটর ট্যুরিজমের মাধ্যমে লেনদেন করার সময় আপনার কাছ থেকে নিম্নলিখিত ব্যক্তিগত সংবেদনশীল তথ্য সংগ্রহ করে, এতে আপনার নাম এবং লিঙ্গ, ফোন নম্বর, বিলিং ঠিকানা এবং সন্তানের ক্ষেত্রে জন্ম তারিখ অন্তর্ভুক্ত থাকে।<br /><br />ন্যাভিগেটর ট্যুরিজম ব্যবহারকারী বা গ্রাহকের সম্মতি ব্যতীত উপরোক্ত পূর্বোক্ত তথ্যের কোনটির উপর বিক্রি বা বাণিজ্য করে না। ব্যবহারকারী/গ্রাহক/ভ্রমণকারীদের কাছ থেকে সংগৃহীত পূর্বোক্ত তথ্য নিম্নোক্ত কাজে লাগানো হয়েছে:<br /><br />গ্রাহকের নাম, ঠিকানা, ফোন নম্বর, ভ্রমণকারীর নাম এবং বয়স প্রযোজ্য সরবরাহকারীদের সাথে শেয়ার করা হয় যেমন এয়ারলাইনস, হোটেল ইত্যাদি, গ্রাহক/ভ্রমণকারীর জন্য পরিষেবাগুলি সংরক্ষণ এবং বুকিংয়ের উদ্দেশ্যে।<br /><br />ফোন নম্বর, ইমেল ঠিকানা, এবং বিলিং ঠিকানার মতো তথ্য প্রচারমূলক উদ্দেশ্যে ব্যবহার করা যেতে পারে যদি না গ্রাহক/ব্যবহারকারী এই ধরনের পরিষেবাগুলি থেকে সদস্য পদ ত্যাগ করেন। আপনি যদি এই তথ্য ভাগ না করা বেছে নেন, আপনি এখনও নেভিগেটর ট্যুরিজম ওয়েবসাইট দেখতে পারেন, তবে আপনি কিছু বিকল্প, অফার এবং পরিষেবাগুলি অ্যাক্সেস করতে অক্ষম হতে পারেন৷<br /><br />ন্যাভিগেটর ট্যুরিজম আপনার আমাদের সাথে শেয়ার করা তথ্য রক্ষা করার জন্য যথাযথ পদক্ষেপ নেয়। অননুমোদিত অ্যাক্সেস এবং অনুপযুক্ত ব্যবহার বা প্রকাশ থেকে আপনার ব্যক্তিগতভাবে সনাক্তযোগ্য তথ্যের গোপনীয়তা রক্ষা করার জন্য আমরা প্রযুক্তি এবং নিরাপত্তা বৈশিষ্ট্য এবং কঠোর নীতি নির্দেশিকা বাস্তবায়ন করেছি। একটি নির্দিষ্ট লেনদেনে আপনার ব্যক্তিগত তথ্য অ্যাক্সেস করতে হবে এমন নির্দিষ্ট সত্তার নাম এবং ঠিকানা পেতে অনুগ্রহ করে info@navigatortourism.com এ আমাদের সাথে যোগাযোগ করুন।<br /><br />আপনি আমাদের সাথে যোগাযোগ করে আপনার তথ্য মুছে ফেলার অনুরোধ করতে পারেন।<br /><br />ন্যাভিগেটর ট্যুরিজম নতুন প্রযুক্তি উপলব্ধ হওয়ার সাথে সাথে তার সুরক্ষা পদ্ধতিগুলিকে উন্নত করতে থাকবে এবং নিশ্চিত করে যে এর নিরাপত্তা পদ্ধতিগুলি বর্তমান প্রযোজ্য প্রবিধানগুলির সাথে সঙ্গতিপূর্ণ।<br /><br />আমাদের গোপনীয়তা নীতি ভবিষ্যতে পরিবর্তন হলে, এটি এখানে পোস্ট করা হবে এবং একটি নতুন কার্যকর তারিখ দেখানো হবে৷ আপনি আমাদের বর্তমান নীতিগুলি বুঝতে পেরেছেন তা নিশ্চিত করতে আপনার নিয়মিত আমাদের গোপনীয়তা নীতি অ্যাক্সেস করা উচিত।<br /><br />*সমস্ত মূল্য এবং অফার প্রাপ্যতার সাথে পরিবর্তন সাপেক্ষে।</p>
                </div>
            </div>
        </Layout>
    )
}

export default privacyPolicy