import React from 'react'
import Layout from '../components/Layout'

const refund = () => {
    return (
        <Layout>
            <div className="row justify-content-center">
                <div className="col-8">
                    <h3 className="text-center">Refund/ Re-issue Policy</h3>
                    <br />
                    <h6 className="about-sub text-left">Flight</h6>
                    <p className="about-detail">Vromon Aviation follows airline's cancellation and re-issue policy.<br /><br />To cancel/ re-issue, travelers are advised to confirm Vromon Aviation 48 hours prior to the travel date. Otherwise, no-show charge might be applicable depending on the airline's rule.<br /><br />To cancel/ re-issue, travelers need to call at +880 1980-011106 or knock on Messenger <br /><br />m.me/NavigatorToursTravel. Our team will initiate an email and solve the issue upon confirmation from the customer.<br /><br />Cancellation fee and a Standard service charge may apply in case of any change.<br /><br />Cancellation fee is shared by the Airlines and may get changed at any time.<br /><br />Refund Amount = Paid Amount - Airline's Cancellation Fee - Admin Fee<br /><br />Re-issue Fee = Airline's Charge Fee + Fare Difference (If any)<br /><br />For Domestic Flight, refund will get initiated (if applicable) after a successful cancellation and refunded amount may reflect in your account within 3 to 7 working days depending on your bank. For International Flight, it may take up to 3 weeks to process the refund and reflect in your account depending on the airline and your bank.<br /><br />*Convenience fee is charged by the service provider & it is non-refundable.</p>
                    <h6 className="about-sub text-left">Hotel</h6>
                    <p className="about-detail">Vromon Aviation follows hotel’s cancellation policy.<br /><br />Cancellation fee may apply depending on the property and the time of cancellation.<br /><br />Date change is not possible for any hotel booking. Customer needs to cancel the previous booking and rebook with the new date.<br /><br />Booking for black-out dates are not cancellable or refundable.<br /><br />Refund will get initiated (if applicable) after a successful cancellation and refunded amount may reflect in your account within 3 to 7 working days depending on your bank.<br /><br />*Convenience fee is charged by the service provider & it is non-refundable.</p>
                    <h6 className="about-sub text-left">Package</h6>
                    <p className="about-detail">Vromon Aviation follows package operator’s cancellation policy.<br /><br />Please check the given policy under each tour before booking.<br /><br />Booking for black-out dates are not cancellable or refundable.<br /><br />Refund will get initiated (if applicable) after a successful cancellation and the refunded amount may reflect in your account within 3 to 7 working days depending on your bank.<br /><br />*Convenience fee is charged by the service provider & it is non-refundable.</p>
                    <h6 className="about-sub text-left">ফ্লাইট</h6>
                    <p className="about-detail">নেভিগেটর ট্যুরিজম এয়ারলাইন বাতিল এবং পুনরায় ইস্যু নীতি অনুসরণ করে।<br /><br />বাতিল/পুনরায় ইস্যু করতে, ভ্রমণকারীদের ভ্রমণের তারিখের 48 ঘন্টা আগে নেভিগেটর ট্যুরিজম নিশ্চিত করার পরামর্শ দেওয়া হচ্ছে। অন্যথায়, এয়ারলাইন্সের নিয়মের উপর নির্ভর করে নো-শো চার্জ প্রযোজ্য হতে পারে।<br /><br />বাতিল/পুনরায় ইস্যু করতে, ভ্রমণকারীদের +880 1980-011106 নম্বরে কল করতে হবে বা মেসেঞ্জারে নক করতে হবে<br /><br />m.me/NavigatorToursTravel. আমাদের দল ইমেলই যোগাযোগ শুরু করবে এবং গ্রাহকের কাছ থেকে নিশ্চিত হওয়া পর্যন্ত সমস্যাটি সমাধান করার চেষ্টা করবে।<br /><br />কোনো পরিবর্তনের ক্ষেত্রে বাতিলকরণ ফি এবং একটি স্ট্যান্ডার্ড সার্ভিস চার্জ প্রযোজ্য হতে পারে।<br /><br />বাতিলকরণ ফি এয়ারলাইন্স দ্বারা ভাগ করা হয় এবং যে কোনো সময় পরিবর্তন হতে পারে।<br /><br />রিফান্ডের পরিমাণ = প্রদত্ত পরিমাণ - এয়ারলাইনের বাতিলকরণ ফি - অ্যাডমিন ফি<br /><br />রি-ইস্যু ফি = এয়ারলাইনের চার্জ ফি + ভাড়ার পার্থক্য (যদি থাকে)<br /><br />ডোমেস্টিক ফ্লাইটের জন্য, একটি সফল বাতিলকরণের পরে ফেরত দেওয়া শুরু হবে (যদি প্রযোজ্য হয়) এবং আপনার ব্যাঙ্কের উপর নির্ভর করে 3 থেকে 7 কার্যদিবসের মধ্যে ফেরত দেওয়া পরিমাণ আপনার অ্যাকাউন্টে প্রতিফলিত হতে পারে। আন্তর্জাতিক ফ্লাইটের জন্য, রিফান্ড প্রক্রিয়া করতে এবং এয়ারলাইন এবং আপনার ব্যাঙ্কের উপর নির্ভর করে আপনার অ্যাকাউন্টে প্রতিফলিত হতে 3 সপ্তাহ পর্যন্ত সময় লাগতে পারে।<br /><br />*সুবিধা ফি পরিষেবা প্রদানকারী দ্বারা চার্জ করা হয় এবং এটি অ ফেরতযোগ্য।</p>
                    <h6 className="about-sub text-left">হোটেল</h6>
                    <p className="about-detail">নেভিগেটর ট্যুরিজম হোটেলের বাতিলকরণ নীতি অনুসরণ করে।<br /><br />বাতিলকরণ ফি সম্পত্তি এবং বাতিলের সময়ের উপর নির্ভর করে প্রযোজ্য হতে পারে।<br /><br />কোনো হোটেল বুকিংয়ের জন্য তারিখ পরিবর্তন সম্ভব নয়। গ্রাহককে আগের বুকিং বাতিল করতে হবে এবং নতুন তারিখের সাথে পুনরায় বুক করতে হবে।<br /><br />ব্ল্যাক-আউট তারিখের জন্য বুকিং বাতিলযোগ্য বা ফেরতযোগ্য নয়।<br /><br />একটি সফল বাতিলকরণের পরে ফেরত দেওয়া শুরু হবে (প্রযোজ্য হলে) এবং ফেরতের পরিমাণ আপনার ব্যাঙ্কের উপর নির্ভর করে 3 থেকে 7 কার্যদিবসের মধ্যে আপনার অ্যাকাউন্টে প্রতিফলিত হতে পারে।<br /><br />*সুবিধা ফি পরিষেবা প্রদানকারী দ্বারা চার্জ করা হয় এবং এটি অ ফেরতযোগ্য।</p>
                    <h6 className="about-sub text-left">প্যাকেজ</h6>
                    <p className="about-detail">নেভিগেটর ট্যুরিজম প্যাকেজ অপারেটরের বাতিলকরণ নীতি অনুসরণ করে।<br /><br />বুকিং করার আগে প্রতিটি ট্যুরের অধীনে প্রদত্ত নীতি চেক করুন.<br /><br />ব্ল্যাক-আউট তারিখের জন্য বুকিং বাতিলযোগ্য বা ফেরতযোগ্য নয়।<br /><br />একটি সফল বাতিলকরণের পরে ফেরত দেওয়া শুরু হবে (যদি প্রযোজ্য হয়) এবং আপনার ব্যাঙ্কের উপর নির্ভর করে 3 থেকে 7 কার্যদিবসের মধ্যে ফেরত দেওয়া পরিমাণ আপনার অ্যাকাউন্টে প্রতিফলিত হতে পারে।<br /><br />*সুবিধা ফি পরিষেবা প্রদানকারী দ্বারা চার্জ করা হয় এবং এটি অ ফেরতযোগ্য।</p>
                </div>
            </div>
        </Layout>
    )
}

export default refund