import React from 'react'
import Layout from '../components/Layout'

const terms = () => {
    return (
        <Layout>
            <div className="row justify-content-center">
                <div className="col-8">
                    <h3 className="text-center">Terms and Conditions</h3>
                    <br />
                    <h6 className="about-sub text-left">Terms & Conditions</h6>
                    <p className="about-detail">Please carefully read the terms and conditions before using any of the services provided by Navigator Tourism. By using any materials, information, products or services of Navigator Tourism, you agree to these terms and conditions. Navigator Tourism holds the right to change or modify these terms and conditions at any time for any reason, without prior notice. Your continued use of the website and its services means you have accepted the modified terms and conditions. Please review the terms periodically to ensure you are up to date regarding the terms and conditions.</p>
                    <h6 className="about-sub text-left">General Disclaimer</h6>
                    <p className="about-detail">Navigator Tourism does not own any travel products. We are simply the bridge which connects the travelers with the travel service providers like airlines, hotels, tour operators etc. The accuracy, completeness, and correctness of the inventory-related information displayed on the Site remain the sole responsibility of each provider. Changes in market conditions or circumstances may occur on short notice which may make information displayed on the Site inaccurate or outdated.<br /><br /> If something should go wrong during booking or travel period, Navigator Tourism will act as a point of contact and will use its commercially reasonable efforts to assist the customer. Navigator Tourism will always follow the standard policies of travel providers (Airlines, Hotel, Tour Operator etc.).</p>
                    <h6 className="about-sub text-left">Booking Terms</h6>
                    <p className="about-detail">If you make a booking through our website for travel products, that booking is made with the travel provider named on the booking page and our website only acts as a user interface. Travelers must understand and agree to the terms and conditions of the travel providers (Airlines, Hotels, Tour Operators etc.) before booking or purchasing their products through Navigator Tourism. If any traveler faces any issue or dispute regarding any of the bookings, Navigator Tourism will act as a point of contact and will use its commercially reasonable efforts to assist the customer.<br /><br />*All prices and offers are subject to change with availability.</p>
                    <h6 className="about-sub text-left">Promotion Terms</h6>
                    <p className="about-detail">Navigator Tourism generates promotion codes/ discounts from time to time which may be availed on the site.<br /><br />Navigator Tourism reserves the right to add, alter, modify, withdraw all or any of the Terms and Conditions or replace, wholly or in part, the program by any other program, whether similar to this program or not or withdraw it altogether without any prior notice.<br /><br />In case of dispute with any party, Navigator Tourism’s decision will be binding and final.<br /><br />When you register with navigatortourism.com, we or any of our partners/affiliate/group companies may contact you from time to time to provide the offers/information of such products/services that we believe may benefit you.</p>
                    <h6 className="about-sub text-left">Payment Terms</h6>
                    <p className="about-detail">By making a payment using this site, you agree to the use of your personal details for verification and validation of your transactions to ensure no one else is using your credentials without your consent. You must also acknowledge that the details you provide us may be disclosed to third-party credit card payment gateway agencies for verification. Your personal details will not be used for any other purposes except to verify and confirm your identity.<br /><br />* In case of national emergency/ lockdown/ political unrest/ natural disaster etc., standard refund policy may not be applicable.</p>
                    <h6 className="about-sub text-left">শর্তাবলী</h6>
                    <p className="about-detail">ন্যাভিগেটর ট্যুরিজম দ্বারা প্রদত্ত যেকোন পরিষেবাগুলি ব্যবহার করার আগে দয়া করে সাবধানে শর্তাবলী পড়ুন৷ ন্যাভিগেটর ট্যুরিজমের যেকোনো উপকরণ, তথ্য, পণ্য বা পরিষেবা ব্যবহার করে আপনি এই শর্তাবলীতে সম্মত হবেন। ন্যাভিগেটর ট্যুরিজম পূর্ব নোটিশ ছাড়াই যেকোনো কারণে যেকোনো সময় এই শর্তাবলী পরিবর্তন করার অধিকার রাখে। ওয়েবসাইট এর পরিষেবাগুলি আপনি ব্যবহার করে পরিবর্তিত শর্তাবলী স্বীকার করেছেন যে আপনি নিয়ম ও শর্তাবলী সম্পর্কে অবগত তা নিশ্চিত করতে অনুগ্রহ করে পর্যায়ক্রমে শর্তাবলী পর্যালোচনা করুন।</p>
                    <h6 className="about-sub text-left">ডিসক্লেইমার</h6>
                    <p className="about-detail">নেভিগেটর ট্যুরিজম কোনো ভ্রমণ পণ্যের মালিক নয়। আমরা কেবল একটি সেতু যা ভ্রমণকারীকে ভ্রমণ পরিষেবা প্রদানকারীদের সাথে সংযুক্ত করে এমন একটি মাধ্যম, যেমন এয়ারলাইন্স, হোটেল, ট্যুর অপারেটর ইত্যাদি। সাইটে প্রদর্শিত ইনভেন্টরি-সম্পর্কিত তথ্যের নির্ভুলতা, সম্পূর্ণতা এবং সঠিকতা প্রতিটি প্রদানকারীর একমাত্র দায়িত্ব থাকে। বাজারের অবস্থা বা পরিস্থিতি যেকোনো সময় পরিবর্তন ঘটতে পারে যা সংক্ষিপ্ত নোটিশে বা সাইটে প্রদর্শিত তথ্যকে ভুল বা পুরানো করে দিতে পারে।<br /><br />বুকিং বা ভ্রমণের সময় কিছু ভুল হলে, নেভিগেটর ট্যুরিজম যোগাযোগের মাধ্যম হিসাবে কাজ করবে এবং গ্রাহককে সহায়তা করার জন্য বাণিজ্যিকভাবে যুক্তিসঙ্গত প্রচেষ্টা করবে। নেভিগেটর ট্যুরিজম সবসময় ভ্রমণ প্রদানকারীদের (এয়ারলাইনস, হোটেল, ট্যুর অপারেটর ইত্যাদি) স্ট্যান্ডার্ড নীতি অনুসরণ করবে।</p>
                    <h6 className="about-sub text-left">বুকিং শর্তাবলী</h6>
                    <p className="about-detail">আপনি যদি ভ্রমণ পণ্যগুলির জন্য আমাদের ওয়েবসাইটের মাধ্যমে একটি বুকিং করেন, তবে বুকিং পৃষ্ঠায় নাম দেওয়া ভ্রমণ প্রদানকারীর সাথে বুকিং করা হয় এবং আমাদের ওয়েবসাইট শুধুমাত্র একটি ব্যবহারকারী ইন্টারফেস হিসাবে কাজ করে। ন্যাভিগেটর ট্যুরিজমের মাধ্যমে তাদের পণ্য বুকিং বা কেনার আগে ভ্রমণকারীদের অবশ্যই ভ্রমণ প্রদানকারীদের (এয়ারলাইনস, হোটেল, ট্যুর অপারেটর ইত্যাদি) শর্তাবলী বুঝতে হবে এবং সম্মত হতে হবে। যদি কোনো ভ্রমণকারী কোনো বুকিং সংক্রান্ত কোনো সমস্যা বা বিবাদের সম্মুখীন হয়, তাহলে ন্যাভিগেটর ট্যুরিজম যোগাযোগের মাধ্যম হিসেবে কাজ করবে এবং গ্রাহককে সহায়তা করার জন্য বাণিজ্যিকভাবে যুক্তিসঙ্গত প্রচেষ্টা করবে।<br /><br />*সমস্ত মূল্য এবং অফার যে কোন সময় পরিবর্তন, সংশোধন বা প্রত্যাহার হতে পারে।</p>
                    <h6 className="about-sub text-left">প্রোমোশন শর্তাবলী</h6>
                    <p className="about-detail">নেভিগেটর ট্যুরিজম সব সময়ে প্রচার কোড/ডিসকাউন্ট তৈরি করে যা সাইটে পাওয়া যেতে পারে।<br /><br />ন্যাভিগেটর ট্যুরিজম যেকোনো শর্ত ও শর্তাবলী যোগ, পরিবর্তন, সংশোধন, বা প্রত্যাহার করার বা অন্য কোনো প্রোগ্রাম দ্বারা সম্পূর্ণ বা আংশিকভাবে প্রতিস্থাপন করার অধিকার সংরক্ষণ করে, এই প্রোগ্রামের অনুরূপ হোক বা না হোক বা কোনো পূর্ব শর্ত ছাড়াই সম্পূর্ণভাবে প্রত্যাহার করার অধিকার রাখে।<br /><br />কোনো পক্ষের সাথে বিরোধের ক্ষেত্রে, নেভিগেটর ট্যুরিজমের সিদ্ধান্ত বাধ্যতামূলক এবং চূড়ান্ত হবে।<br /><br />আপনি যখন navigatortourism.com-এর সাথে নিবন্ধন করবেন, তখন আমরা বা আমাদের অংশীদার/অধিভুক্ত/গ্রুপ কোম্পানিগুলির মধ্যে যেকোনও পণ্য/পরিষেবার অফার/তথ্য প্রদানের জন্য যেকোনও সময়ে আপনার সাথে যোগাযোগ করতে পারে যা আমরা বিশ্বাস করি যে আপনার উপকার হতে পারে।</p>
                    <h6 className="about-sub text-left">লেনদেন শর্ত</h6>
                    <p className="about-detail">এই সাইটটি ব্যবহার করে অর্থপ্রদান করার মাধ্যমে, আপনি আপনার লেনদেনের যাচাইকরণ এবং বৈধতার জন্য আপনার ব্যক্তিগত বিবরণ ব্যবহারে সম্মত হন যাতে আপনার অনুমতি ছাড়া অন্য কেউ আপনার প্রশংসাপত্র ব্যবহার করছে না। আপনাকে অবশ্যই স্বীকার করতে হবে যে আপনি আমাদের যে বিশদ প্রদান করেন তা যাচাইয়ের জন্য তৃতীয় পক্ষের ক্রেডিট কার্ড পেমেন্ট গেটওয়ে এজেন্সির কাছে প্রকাশ করা হতে পারে। আপনার ব্যক্তিগত বিবরণ আপনার পরিচয় যাচাই এবং নিশ্চিত করা ছাড়া অন্য কোনো উদ্দেশ্যে ব্যবহার করা হবে না।<br /><br />* জাতীয় জরুরি অবস্থা/লকডাউন/রাজনৈতিক অস্থিরতা/প্রাকৃতিক দুর্যোগ ইত্যাদির ক্ষেত্রে, স্ট্যান্ডার্ড রিফান্ড নীতি প্রযোজ্য নাও হতে পারে </p>

                </div>
            </div>
        </Layout>
    )
}

export default terms